### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by marcusvinnicius** [pazindorb/dc20rpg#10]
When I try to install from  the manifest address  I got this error:
[undefined] Cannot read properties  of null (reading "Iid)

**Comment by pazindorb** [comment]
Make sure you are pasting manifest url as a system not world or module 
![image](https://github.com/user-attachments/assets/cb423ee1-404b-4dca-a594-26534dc39834)

**Comment by marcusvinnicius** [comment]
Just to be sure, I typed the following URL:
https://github.com/pazindorb/dc20rpg/releases/download/0.8.1/system.json
and get the following result
![Captura de tela 2024-07-27 185943](https://github.com/user-attachments/assets/0657fbac-251a-472f-bf98-ae795658748d)

**Comment by emile-tawfik** [comment]
You are trying to install a system as a world.

**Comment by marcusvinnicius** [comment]
Oh that was stupid of me. Thank you for your patience.
