### ISSUE TITLE
Incorrect starting skill points when making new character

### ISSUE THREAD

**Issue by OmarMAbbasi** [pazindorb/dc20rpg#12]
When making a new character, starting skill points are 0-INT instead of 5-INT

![image](https://github.com/user-attachments/assets/426e0706-5641-4427-be70-111aecd9116b)

**Comment by pazindorb** [comment]
Starting Skill, Trade and Language points come from background. You need to add one to your character sheet. You can open background compendium from character sheet
![image](https://github.com/user-attachments/assets/2c1f519b-3fcc-4622-aeb8-8207bccd57aa)
