### ISSUE TITLE
[BUG] Multiple instances of an actor produces multiple instances in Combat Tracker upon rolling initiative.

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#18]
Reproduce:

Load multiple instances of an actor onto a scene (non-monster, I believe). 
Add one of the instances to Combat
Roll initiative
Multiple copies will be added to Combat Tracker- one for each actor. 

This may be intentional, but if so I find it to remove control. If this were an option to facilitate quick rolling of multiple actors, great, but as an option.

**Comment by pazindorb** [comment]
This is a default foundry behavior. The same thing happens in DnD 5e. But you are right. I will override it.
