### ISSUE TITLE
[BUG] Fonts not loading correctly for dropdown menus in Firefox Browser

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#20]
Fonts look the same in Foundry app and Chrome, but not Firefox. I suspect the stylesheet is not loading correctly?

### Firefox:
![image](https://github.com/user-attachments/assets/9ff40d7e-9944-4a71-ad32-79a3eccee825)
![image](https://github.com/user-attachments/assets/2a3b2c4b-1323-46c3-83ce-e2a7abe73438)

### Chrome:
![image](https://github.com/user-attachments/assets/37a9dc72-6932-42c1-90e8-8531dd53fe6c)
![image](https://github.com/user-attachments/assets/ee633a20-067d-4ca2-b829-b81673fad392)

### Foundry:
![image](https://github.com/user-attachments/assets/c63fd492-a519-4dfa-8423-b90d6fde1f55)
![image](https://github.com/user-attachments/assets/bd741795-d02b-4d57-9e08-6c65cfa117e6)

**Comment by pazindorb** [comment]
Note to myself: Somebody had similar problem with Firefox [here](https://www.outsystems.com/forums/discussion/82972/custom-font-works-in-chrome-but-not-firefox-dropdowns/).
