### ISSUE TITLE
[SUGGESTION] Add the existing Condition Stack Counter Number to On-Screen Condition Display

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#27]
The conditions tracker in the top right shows multiple instances of a condition if it is stacking. 

The same in the Effects tab displays a number displaying how many instances of the condition exist. 

I love the conditions tab solution, why not do the same for the HUD? It's quite elegant!

### HUD Conditions:
![image](https://github.com/user-attachments/assets/9fc60e24-7ff1-4f58-9d69-8bd5d976c0ea)

### Effects Tab:
![image](https://github.com/user-attachments/assets/1f0507a5-ef48-4119-8960-8969615d2c15)

**Comment by SirJohn13** [comment]
Agreed!
