### ISSUE TITLE
[POSSIBLE BUG] Roll Request actor list inconsistent, unsure how to use.

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#31]
One time I opened the menu and two party PCs appeared. At the same time, my second GM account only displayed two skeletons. Upon refresh, there were no options.

Selecting, targeting, adding to combat, adding to party, and adding to scene do not determine what appears in this list. What does?

### List with Skeleton actors:
![image](https://github.com/user-attachments/assets/2899a60f-9796-4b60-ac84-d200b8f44da6)

**Comment by pazindorb** [comment]
I've never tried this with 2 GM accounts active at the same time. The purpose of this window is to collect actors belonging to currently active players. I will make sure no GM account is included there. This problem occurs because when a GM creates a new actor, he also becomes its owner.
