### ISSUE TITLE
[REQUEST] Moving during combat consumes AP

### ISSUE THREAD

**Issue by Riv3nOne** [pazindorb/dc20rpg#38]
### Description
Moving a token during an active combat encounter consumes an AP for every increment of an actor's allowable speed.

### Function
- Fay has ground speed 5
- When under combat movement controls, moving Fay's token 1-5 space(s), consumes 1 AP
- Should be tracked to allow for split movements, so only 1 AP is consumed, creating a "pool" of 5 movement spaces
- Moving the token beyond 5 spaces, consumes another AP and awards up to 5 more spaces [allowable up to the actor's total available APs].

### Example
Fay slides her token 3 spaces away from her target, she automatically consumes 1 AP. She then attacks a target with her bow giving herself advantage, expending an additional 2 AP. She then moves her target 7 more spaces to increase her room, using the remaining 2 spaces from her first move and consuming an additional AP to move the extra 5 spaces.

### Implementation/coding [a recommendation]
1. trigger event on token movement
2. validate/create a movement pool
3. evaluate movement pool value
4. if empty, evaluate AP remaining, if >0, consume 1 AP to add spaces to pool
5. subtract the # of spaces moved from the pool
6. if more spaces remain, repeat steps 3-5
7. if spaces remain beyond movement pool and total AP, warn player movement exceeds their AP & speed [optional: return token to origin point]

**Comment by WThunderspirit** [comment]
mirrored: https://github.com/pazindorb/dc20rpg/issues/35
