### ISSUE TITLE
[BUG] The foot moveth.

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#40]
The Ground Speed icon moves during mouseover. Probably the dynamic JS on-hover grabs an id that includes the foot image field.

![image](https://github.com/user-attachments/assets/357cdaa1-c4b5-4f30-8b4b-b69391e367f7)
Normal

![image](https://github.com/user-attachments/assets/f30d8f6d-4ab3-4f0c-84ab-9ced455fe298)
Moves a little itty bitty distance.

**Comment by pazindorb** [comment]
Well that is not a bug it is a feature. I can say that for the first time in my life :D

**Comment by Friendly-Mushrooom** [comment]
Haha I was thinking "This might be a feature. This might be a feature. It's a fun little movement and it seems intentional..."

You got to say the line, Bart! :)
