### ISSUE TITLE
[BUG] "Show in Table Mode" for Resistance and Immunities in Core Tab makes them disappear.

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#43]
Clicking the "Show in Table Mode" button for Resistance and Immunities in Core Tab causes the fields to disappear entirely. This persists between opening and closing the actor sheet. The child divs within first-row are deleted and nothing replaces them.

![image](https://github.com/user-attachments/assets/3c3eaab9-a6b1-4868-b1b1-50753834db79)
None clicked

![image](https://github.com/user-attachments/assets/53a4cb6c-f2f5-4c6a-a080-a0eac393b868)
Resistances clicked

![image](https://github.com/user-attachments/assets/f74a8b09-7f55-4597-bfff-a70f73cfa2d0)
Both clicked

**Comment by pazindorb** [comment]
Those do not disappear. Resistance and Immunities tables are bellow the skill tables.
![image](https://github.com/user-attachments/assets/327a1fb7-f8a5-4db9-9d9a-38853a2d4830)

**Comment by Friendly-Mushrooom** [comment]
That they are! I did not see that since I didn't scroll down!

Lovely option, thank you sir!
