### ISSUE TITLE
[SUGGESTION] Distinguish between different "You Have Gained New Features" windows

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#44]
"You have gained new features" window appearing multiple times feels weird. I understand that they are coming from different places on the back end i.e. ancestry or class. Could that origin be shared with the user? If not, could these windows (the non-interactive ones) be combined?

**Comment by pazindorb** [comment]
I will add option to provide custom window title instead of default You gain Features, it should do the trick,
