### ISSUE TITLE
[SUGGESTION] Move the Attributes to the right of the Character Sheet Header

### ISSUE THREAD

**Issue by Friendly-Mushrooom** [pazindorb/dc20rpg#46]
As well as moving Physical Save and Mental Save under "Checks & Saves" as I mentioned in another issue, I think that placing the attributes beside the checks and saves makes more sense, as they play against each other. Maybe attributes between that and the speed/defense, so you can reference it. 

I also think having the health, AP, MP, SP, etc all on the left works better.

Plus it looks prettier to me. Look, the dragon face appears in the empty space now! Wow!

## Far Right
![image](https://github.com/user-attachments/assets/e2fafe3a-ecc3-46b3-8831-646438b0b515)

## Between
![image](https://github.com/user-attachments/assets/40b63e0d-be35-40b6-a143-4d5b77b3f53a)

### Original for Reference
![image](https://github.com/user-attachments/assets/9f78df0a-40fc-4484-83ac-2fe0361d04e8)

**Comment by Nublaglasiem** [comment]
I'm Okay with how it's done right now

**Comment by pazindorb** [comment]
For now I will keep it as it is, we will see what will happened in the future :D

**Comment by Friendly-Mushrooom** [comment]
Fair enough! If things changed my suggestion is likely totally irrelevant now anyway.

I will say, however it ends up, I quite like seeing the wittle dragon face peeking 👀👀👀
