### ISSUE TITLE
[SUGGESTION] Clarify Ancestry Features Window in Character Creation Wizard

### ISSUE THREAD

**Issue by SirJohn13** [pazindorb/dc20rpg#47]
Amazing work in the new update!
I got some quick feedback on the character creator

The window where you select ancestry features doesn't say or has any mention to ancestry.
It took my a little bit to realize those were the ancestry features. I can see a new player getting confused.

Why is it confusing:
1. There's no mention of it been ancestry features
2. Selecting ancestries and ancestry features don't occur in sequential order (seems like a designed flow, not necessarily a problem) 

Possible solutions:
1. Make it clear that it's the ancestry features. Example "You gain the following ANCESTRY features" or "Choose your ANCESTRY features"
2. Make ancestry and features appear in sequential order (Choose ancestry > choose ancestry features)

**Comment by Friendly-Mushrooom** [comment]
I'd say that lumps in nicely with [This issue](https://github.com/pazindorb/dc20rpg/issues/44)
