### ISSUE TITLE
[FR] Export functions

### ISSUE THREAD

**Issue by mrcomac** [pazindorb/dc20rpg#48]
Hi there,

I'm raising this feature request to make easy to build HUDs for DC20RPG.

I would like to have access to the functions `rollPrompt` and `promptItemRoll`;

Can you please share those functions as following:
```
CONFIG.DC20RPG.rollPrompt = rollPrompt;
CONFIG.DC20RPG.promptItemRoll = promptItemRoll;
```

If that isn't the right way to trigger rolls in the system, please let me know.

**Comment by pazindorb** [comment]
Hi it is correct way. I did exported those methods already in the last update. Here are the paths
`game.dc20rpg.tools.promptRoll`
`game.dc20rpg.tools.promptItemRoll`

If those are not accessible for you (I dont know much about module development) I will export them in the way you want me to.

**Comment by mrcomac** [comment]
That should work.

I didn't realise the system has a new version.

Thank you :)
