### ISSUE TITLE
[FEATURE REQUEST] Add createRestDialog to the tools available outside the system

### ISSUE THREAD

**Issue by mrcomac** [pazindorb/dc20rpg#49]
Hello @pazindorb

The function `createRestDialog` isn't available from the `game.dc20rpg.tools`. Can you please add that?

Thank you

**Comment by mrcomac** [comment]
Hi @pazindorb ,

Just identified another good one to be in the same list of shared functions `promptActionRoll`.

Thank you

**Comment by pazindorb** [comment]
Hi, just want to let you know since I will close that issue.  `createRestDialog` will be added to tools (let me know if you need some more things there) and  `promptActionRoll` wont be needed anymore since in the next update  all basic actions will become items.
