### ISSUE TITLE
[FEATURE REQUEST] Automatically Apply Run Roll Level Check

### ISSUE THREAD

**Issue by SirJohn13** [pazindorb/dc20rpg#50]
Hi, it it possible to automatically run the "run roll level check" when opening an action window?

Maybe as toggleable option in the settings for those that want the automation

**Comment by Friendly-Mushrooom** [comment]
Some degree of automation would be really nice here. 

In a [previous, closed issue](https://github.com/pazindorb/dc20rpg/issues/29#issue-2513178955) I noted, edited:

I think a LOT of players would forget to click the check often. Perhaps instead there could be a highlight to show that things _would_ change if it were clicked? A glowing outline to remind people "Hey! There are modifications that are supposed to happen here if you want them!"

I recognize that that may require a lot of calls to whatever function(s) handle that. Maybe it can be called when the window first opens and upon mouseover of the "roll" button, then the level check would change colors to remind the player?

**Comment by Nublaglasiem** [comment]
I completely support this idea, my players are often forgetting to check roll level and making it more automated is a really huge help!

As mentioned my Friendly-Mushroom, it could be the "reminder" type, but I personally prefer a setting option of "Always apply the Roll Level upon opening a Roll Popup". If those two could be made - that would be amazing!

**Comment by pazindorb** [comment]
I will go with reminder. Player opens roll window -> Roll Check button will pulse with red light until clicked
![image](https://github.com/user-attachments/assets/8777d366-b1aa-484e-8aa8-cefa2dae089d)

**Comment by Friendly-Mushrooom** [comment]
This solution looks great. Good work!
