### ISSUE TITLE
Feature Request: automate Death's Door mechanics

### ISSUE THREAD

**Issue by WThunderspirit** [pazindorb/dc20rpg#52]
Would there be a chance to automate these things in the future?

> Death’s Door
> When you are reduced to 0 HP or lower, you suffers the following effects:
> 
> Exhaustion:You immediately gainExhaustion 1.
> Action Point Limit:You can’t spend more than 1 AP until the end of your next turn, until you’re restored to 1 HP or higher.
> Concentration:You can’t Concentrate.
> Death Save:At the end of each of your turns, you make a Death Save.Failure:You take1True damage.Critical Failure:You fallUnconsciousuntil you’re restored to 1 HP or higher.Critical Success:You’re restored to 1 HP.

// determine when a PC (& optionally a lt or boss NPC) is at 0 hp
// determine current exh level
// apply + exh 1
// block out 3 APs to allow only 1 to be spent
// end all concentration & disallow casting concentration spells (or autofail them)
// create the death save button to roll death saves OR automatically prompt a roll when turn ends (Out of combat, roll, then roll again after 1 AP is spent or the arbitrary 1 minute)
// apply effects of death save fails or successes
// loop for each round (or an arbitrary minute? out of combat) until hp = 1+ or Death Threshold is reached

**Comment by pazindorb** [comment]
Hi, most of those things are already one with DC implementation:
- determine when a PC (& optionally a lt or boss NPC) is at 0 hp
- determine current exh level with all things connected to it, so -X to checks, saves, and speed
- apply + exh 1
- automatically prompt death save a roll when turn ends in combat (and you are unstable, you roll your saves only when you are unstable)
- apply effects of death save fails or successes

What is not currently in the system: 
- block out 3 APs to allow only 1 to be spent 
- end all concentration & disallow casting concentration spells (or autofail them) - missed that part of the rules, thanks
- out of combat death saves - most likely I wont do that as I dont want to force things like that outside of combat, I will leave this for the GM to decide when to roll Death Save out of combat

Are you using 0.8.3 version? It requires Foundry v12 so it might not appear on v11 as the most recent one.

**Comment by WThunderspirit** [comment]
OK - stripping to DC20 only = saw the death save and exh in the sheet ... exh seems to be applying to speed and Save DCs
Exh doesn't seem to apply to Saves and checks, as shown in the Death save (as well as others I experimented with.
![capture_001_19112024_154955](https://github.com/user-attachments/assets/079643ae-41ba-4875-8543-6b154b097f1f)
![capture_001_19112024_155356](https://github.com/user-attachments/assets/134b3338-d907-4c26-bd16-c89c7e2e2d95)

**Comment by WThunderspirit** [comment]
PS: Ugh ... _Frail_ and _Gigantborn_ (sp) ... **Flail** and **Giantborn**!

**Comment by pazindorb** [comment]
From what I see exhaustion did applied to your Attack Check. You have exhaustion 2 so -2 to all rolls, your attack modifier would be 4 (3 form Prime + 1 form Combat Mastery) but it is 2 so exhaustion was applied.

When it comes to death saves I thought that those are not affected by exhaustion, but I found discord question where dev said they are. I will make a note of that being the case.

When you fail death save you don't get another stack of exhaustion, you only take 1 True damage. You gain 1 stack of exhaustion when you enter Death's Door.

And you make Death Save only when you are unstable 
![image](https://github.com/user-attachments/assets/bc3782c4-e2b7-4d75-8a9a-8f3007278d22)
