### ISSUE TITLE
[Bug] System Update to 0.8.4 - Breaks monsters

### ISSUE THREAD

**Issue by SirNiloc** [pazindorb/dc20rpg#56]
Update does not add the following 
"basic": {
          "offensive": {
            "name": "Offensive",
            "order": 0,
            "custom": false
          },
          "defensive": {
            "name": "Defensive",
            "order": 1,
            "custom": false
          },
          "utility": {
            "name": "Utility",
            "order": 2,
            "custom": false
          },
          "reaction": {
            "name": "Reaction",
            "order": 3,
            "custom": false
          },
          "skillBased": {
            "name": "Skill Based",
            "order": 4,
            "custom": false
          }
        }
      },
      "actionHeld": {
        "isHeld": false,
        "itemId": null,
        "itemImg": null,
        "apForAdv": null,
        "enhancements": null,
        "mcp": null,
        "rollsHeldAction": false
      },
      "effectsToRemoveAfterRoll": [],
      "headerFilters": {
        "main": "",
        "basic": ""
      }
    },
    "headerFilters": {
      "main": ""
    },
    
    
    
    
    
    Work around
    
    Replace:
    "inventory": {
            "name": "Inventory",
            "order": 4,
            "custom": false
          }
        }
      }
    },
    
    
    
    
    With:
    
    "inventory": {
            "name": "Inventory",
            "order": 4,
            "custom": false
          }
        },
        "basic": {
          "offensive": {
            "name": "Offensive",
            "order": 0,
            "custom": false
          },
          "defensive": {
            "name": "Defensive",
            "order": 1,
            "custom": false
          },
          "utility": {
            "name": "Utility",
            "order": 2,
            "custom": false
          },
          "reaction": {
            "name": "Reaction",
            "order": 3,
            "custom": false
          },
          "skillBased": {
            "name": "Skill Based",
            "order": 4,
            "custom": false
          }
        }
      },
      "actionHeld": {
        "isHeld": false,
        "itemId": null,
        "itemImg": null,
        "apForAdv": null,
        "enhancements": null,
        "mcp": null,
        "rollsHeldAction": false
      },
      "effectsToRemoveAfterRoll": [],
      "headerFilters": {
        "main": "",
        "basic": ""
      }
    },
    "headerFilters": {
      "main": ""
    },

**Comment by pazindorb** [comment]
Hmm. World monsters should be updated by the migration script. The only problem can happend with monsters that are inside of modules. I know that you are the creator of monsters module, I would suggest you to move those to world compendium run migration script with force run ``game.dc20rpg.tools.forceRunMigration("0.8.3", "0.8.4")`` and move those to module again.

In the future I will provide a method to run migration script for module compendiums so devs like you can use that to update module content without manual work.

**Comment by SirNiloc** [comment]
I will keep this in mind, I got it all sorted with JSON but I'll remember this for any future changes.

Thanks!
