### ISSUE TITLE
Add Custom Language Doesn't Work (NPC and PC)

### ISSUE THREAD

**Issue by webmaster94** [pazindorb/dc20rpg#6]
When attempting to add a custom language, the following error is thrown:
![image](https://github.com/user-attachments/assets/16e39513-a043-4f6e-9245-d3961d07cef3)

**Comment by pazindorb** [comment]
Cannot replicate, closing

**Comment by webmaster94** [comment]
It was so many versions ago that I put this in that is is very possible that some update fixed it.
