### ISSUE TITLE
Items/Features Should Display Costs Within Collapsed View

### ISSUE THREAD

**Issue by webmaster94** [pazindorb/dc20rpg#8]
Currently, items do not appear to show costs for their use in either the NPC or PC sheet. It would make things easier if this information can be seen without needing to open up the item sheet.

**Comment by pazindorb** [comment]
![image](https://github.com/user-attachments/assets/58e126bd-b203-450b-892c-c026177284e5)
They should. Look at the image. Maybe item has no usage cost configured.

**Comment by webmaster94** [comment]
Ah, ok it actually does I just didn't connect that symbol with the cost of action points. Maybe a tooltip that gives a numerical value of the action cost when hovered over for more clear UX. I know that symbol makes sense since it is at the top where action points are but I think someone who is new to the system will find that confusing.
